### ISSUE TITLE
number of items other than 5 is not working 

### ISSUE THREAD

**Issue by xnio94** [hacktons/convex_bottom_bar#32]
if the number of items is deferent than five the widget build weirdly 
I think the number 5 is hardcoded somewhere but I'm not sure where

**Comment by avenwu** [comment]
@xnio94 you should provide some code or screenshot. The items count is not hardcode😂.
I guess you're using tabs which broke the count length assertion; 

Th count of items should be an **odd** number, otherwise internal assertion will crash the app at runtime.  
<img width="504" alt="Screen Shot 2020-02-19 at 3 54 27 PM" src="https://user-images.githubusercontent.com/1622234/74813304-260ad080-5330-11ea-8875-9a214c060ff2.png">
But crash you app is kind of terrible case, so we remove the assertion for a while until then we got a better solution.

**Comment by xnio94** [comment]
yeah sorry for not providing more details, i was just testing with this [code example](https://github.com/hacktons/convex_bottom_bar#how-to-use) and changed the items property.
![image](https://user-images.githubusercontent.com/12850284/74815029-bcbb9b00-52f8-11ea-8400-0fe1e215ee81.png)
> I guess you're using tabs which broke the count length assertion;
> Th count of items should be an odd number, otherwise internal assertion will crash the app at runtime

yes that's what happened i didn't know that it only accepts an odd number
> But crash you app is kind of terrible case, so we remove the assertion for a while until then we got a better solution.

yes i understand, and hope it will support even numbers too (all numbers should be equal😂)
anyway thanks for the fast response and for this beautiful package it looks so goood
