### ISSUE TITLE
The 2.4 broke my app build

### ISSUE THREAD

**Issue by talamaska** [hacktons/convex_bottom_bar#85]
**Describe the bug**

Upgrading the lib to 2.4.0 broke my app which is still on Flutter 1.17.5
while this release is pushed to support 1.20, not everybody have migrated.
I was having ^2.3.0 in my pubspec and I got 2.4.0 which was not compiling because of the clipBehavior.

**Environment details**

Paste the flutter environment detail.
```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.959], locale bg-BG)
 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.47.3)
[√] Connected device (1 available)

Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (5 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```
Paste the package version.
```
dependencies:
  convex_bottom_bar: ^2.3.0
```

**To Reproduce**

1. just run flutter pub get today
2. flutter build

**Expected behavior**

Since this release adds a breaking change to support 1.20 you should revoke it and release v3.

**Comment by avenwu** [comment]
**You are right. We should better name it to something v3.** 
I just received too much error reports because of the flutter upgrade before v2.4.0 is released. The breaking change has been supported through separated beta version for a long time when flutter 1.20 is not in stable channel.  

I have to say this change has nothing to do with ConvexAppBar's public API, and not all developers follow the pub version strictly. Since the v2.4.0 has already been shipped. Release to v3 won't undo the broken error. Let's just keep it simple😂.

**Comment by talamaska** [comment]
right, just so you know if someone else cries, It just broke right before I upgraded to 1.20 when I was performing pub get
