### ISSUE TITLE
App bar floats up when textfield tapped

### ISSUE THREAD

**Issue by therealjohnsummer** [hacktons/convex_bottom_bar#9]
When you have the convex bottom bar and a textfield - tapping the textfield displays the on screen keyboard but the convex app bar is scrolled into view when the on screen keyboard appears.

There is a property of a Scaffold called **resizeToAvoidBottomPadding** This normally resolves the issue but the convex bottom bar still appears...

i.e
```

Scaffold(
          resizeToAvoidBottomPadding: false,
          body: _buildMainControlWithTextField(),
          bottomNavigationBar: ConvextBottomAppBarWidget()
);          
```

**Comment by avenwu** [comment]
@therealjohnsummer 
After some tests, the "floating issue" caused by software keyboard can not be reproduced in the demo app. `TextFiled` just work fine with or without **resizeToAvoidBottomPadding** configured.

Please provide more information, such as: 
1. OS， Android or iPhone;
2. are there any unmentioned customization for Activity/ViewController?
3. provide simplified issue project.

**Comment by therealjohnsummer** [comment]
Hi - this was on iPhone X devices. Fixed the issue by detecting when keyboard appears and changing the visibility of the BottomNavigationBar widget - thus , the issue still exists but can get around with this workaround .

Thanks for a great plugin - its perfect.

**Comment by avenwu** [comment]
OK, this issue will be closed,  feel free to open another one if there's any question.
